resources:
  - name: source-repo
    task:
      environment:
        command: sh scripts/clonegit.sh
      source: https://gist.github.com/ae2900ddab30ef7548da6188815ee68b.git

  - name: build-container
    task:
      environment:
        command: sh scripts/downloadcontainer.sh
      source: archlinux:base-devel

  - name: main.o
    resources:
    - name: source-repo
      path: /src/
    - name: build-container
      path: /
    files:
    - name: main.o
      path: /src/main.o
    task:
      environment:
        command: sh scripts/containeronhost.sh
      command: cd /src ; g++ -c main.cpp -o main.o

  - name: executable
    resources:
    - name: main.o
      path: /src
    - name: build-container
      path: /
    - file: config.yml
      content:
        var: dsfasdf
    files:
    - name: main
      path: /src/main
    task:
      environment:
        command: sh scripts/containeronhost.sh
      command: g++ main.o -o main
    
